dataset:
  name: cifar100
  path: ./data
  class: None
  cache: true
  batch_size: 128
  transforms:

model:
  name: resmlp
  num_classes: 100

training:
  device: cuda
  epochs: 75
  optimizer: SGD
  optimizer_args:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.001
    nesterov: True
    fused: True
  scheduler: CosineAnnealingLR
  scheduler_args:
    T_max: 100
    eta_min: 0.0001
#  scheduler: StepLR
#  scheduler_args:
#      step_size: 10
#      gamma: 0.1
  early_stopping:
    enabled: True
    patience: 20
    min_delta: 0.001

logging:
  tensorboard: true
  wandb: true
